name: Run Backend Server

on:
  push:
    branches:
      - main

jobs:
  start-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start backend server
        run: |
          cd backend
          node serwer.js
