name: Run WebSocket Server

on:
  push:
    branches:
      - main

jobs:
  start-websocket-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
        working-directory: backend
          
      - name: Start WebSocket server
        run: |
          echo START
          echo ls
          node backend/serwer.js
          echo KONIEC